name: 'Repo Level Trivy Scan'

on:
  schedule:
    - cron: '0 4 * * *'
  pull_request:

jobs:
  # JOB 1: Build the Docker image directly and push it to GHCR
  build:
    name: 'Build and Push Docker Image'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      image-name: ${{ steps.set-image-name.outputs.image-name }}

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Log in to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This single, standard action replaces all custom build scripts.
      - name: 'Build and push Docker image'
        uses: docker/build-push-action@v6
        with:
          # The build context is the root of the repository
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
          # This is the key: we point directly to the Dockerfile inside the 'build' directory
          file: ./build/Dockerfile

      - name: 'Set image name output'
        id: set-image-name
        run: echo "image-name=ghcr.io/${{ github.repository }}:${{ github.sha }}" >> $GITHUB_OUTPUT

  # JOB 2: Call the reusable organization workflow
  scan:
    name: 'Trigger Organization Scan'
    needs: build
    permissions:
      contents: read
      packages: read
      security-events: write
    uses: newrelic-trivy/.github/.github/workflows/org-level-trivy-scan.yml@main
    with:
      image-name: ${{ needs.build.outputs.image-name }}
    secrets: inherit
